# theme = "golok"
# theme = "catppuccin_mocha"
theme = "ayu_dark"

[keys.normal."\\"]
c = {  o = ":config-open", r = ":config-reload" }
e = { r = ":reload", R=":reload-all", l=":lsp-restart" }
q = ":q"
C = { r = ":sh cargo run" }

[keys.normal]
C-s = ":w!"
tab = ":buffer-next"
S-tab = ":buffer-previous"
A-q = ":buffer-close"
"C-]" = "goto_next_paragraph"
"C-[" = "goto_prev_paragraph"

# Pickers
C-p = "file_picker"
A-p = "buffer_picker"
C-A-p = "symbol_picker"
"=" = "increment"
"minus" = "decrement"

[keys.select]
"=" = "increment"
"minus" = "decrement"

[keys.insert]
"C-[" = "normal_mode"
"C-space" = "completion"

[editor]
bufferline = "multiple"
line-number = "relative"
shell = ["C:\\Program Files\\Git\\bin\\bash.exe", "-c"]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


# Extras
# [editor.whitespace]
# render = "none"

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
