# Rust things

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt" }
auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy" 


# Web things
[language-server]
biome = { command = "biome",  args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [ { name = "biome" }, { name = "typescript-language-server", except-features = [ "format" ] } ]
auto-format = true
formatter = { command = "biome", args = [ "format", "--stdin-file-path", "a.ts" ] }

[[language]]
name = "typescript"
language-servers = [ { name = "biome" }, { name = "typescript-language-server", except-features = [ "format" ] } ]
auto-format = true
formatter = { command = "biome", args = [ "format", "--stdin-file-path", "a.ts" ] }

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "biome" },  { name = "typescript-language-server", except-features = [ "format" ] } ]
formatter = { command = "biome", args = [ "format", "--stdin-file-path", "a.ts" ] }

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "biome" }, { name = "typescript-language-server", except-features = [ "format" ] } ]
formatter = { command = "biome", args = [ "format", "--stdin-file-path", "a.jsx" ] }

[[language]]
name = "json"
language-servers = [ { name = "biome" }, { name = "vscode-json-language-server", except-features = [ "format" ] } ]
formatter = { command = "biome", args = [ "format", "--stdin-file-path", "a.json" ] }


[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "emmet-ls" ]
auto-format = true

[[language]]
name = "css"
language-servers = [ {name = "biome"}, {name = "vscode-css-language-server", except-features = ["format"] }, {name = "emmet-ls" }]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.css"] } 
