
# "ui.background" = { bg = "bg1" } # Default background color (comment if you want background to adapt to the terminal's background)
"ui.window" = { fg = "bg0" } # Window border between splits.
"ui.gutter" = { fg = "fg3" } # Left gutter for diagnostics and breakpoints.

"ui.text" = { fg = "fg1" } # Default text color.
"ui.text.focus" = { bg = "sel1", fg = "yellow" } # Selection highlight in buffer-picker or file-picker.
"ui.text.info" = { fg = "fg3", bg = "sel0" } # Info popup contents (space mode menu).

"ui.cursor" = { bg = "fg3", fg = "bg1" } # Fallback cursor colour, non-primary cursors when there are multiple (shift-c).
"ui.cursor.primary" = { bg = "fg1", fg = "bg1" } # The primary cursor when there are multiple (shift-c).
"ui.cursor.match" = { fg = "green", modifiers = ["bold"] } # The matching parentheses of that under the cursor.

"ui.selection" = { bg = "bg3" } # All currently selected text.
"ui.selection.primary" = { bg = "bg4" } # The primary selection when there are multiple.
"ui.cursorline.primary" = { bg = "bg3" } # The line of the primary cursor (if cursorline is enabled)
# "ui.cursorline.secondary" = { } #	The lines of any other cursors (if cursorline is enabled)
# "ui.cursorcolumn.primary" = { } #	The column of the primary cursor (if cursorcolumn is enabled)
# "ui.cursorcolumn.secondary" = { } #	The columns of any other cursors (if cursorcolumn is enabled)

"ui.linenr" = { fg = "fg3" } # Line numbers.
"ui.linenr.selected" = { fg = "yellow", modifiers = ["bold"] } # Current line number.

# "ui.virtual" = { } # Namespace for additions to the editing area.
"ui.virtual.ruler" = { bg = "bg3" } # Vertical rulers (colored columns in editing area).
"ui.virtual.whitespace" = { fg = "bg3" } # Whitespace markers in editing area.
"ui.virtual.indent-guide" = { fg = "black" } # Vertical indent width guides

"ui.statusline" = { fg = "fg2", bg = "bg0" } # Status line.
"ui.statusline.inactive" = { fg = "fg3", bg = "bg0" } # Status line in unfocused windows.
"ui.statusline.normal" = { bg = "blue", fg = "bg0", modifiers = ["bold"] } # Statusline mode during normal mode (only if editor.color-modes is enabled)
"ui.statusline.insert" = { bg = "green", fg = "bg0", modifiers = ["bold"] } # Statusline mode during insert mode (only if editor.color-modes is enabled)
"ui.statusline.select" = { bg = "magenta", fg = "bg0", modifiers = ["bold"] } # Statusline mode during select mode (only if editor.color-modes is enabled)

"ui.help" = { bg = "sel0", fg = "fg1" } # Description box for commands.

"ui.menu" = { bg = "sel0", fg = "fg2" } # Code and command completion menus.
"ui.menu.selected" = { bg = "fg3" } # Selected autocomplete item.
"ui.menu.scroll"	= { fg = "fg3" } # fg sets thumb color, bg sets track color of scrollbar.

"ui.popup" = { bg = "bg0", fg = "fg1" } # Documentation popups (space-k).
"ui.popup.info" = { bg = "sel0", fg = "fg1" } # Info popups box (space mode menu).

"markup.raw" = { fg = "magenta" } # Code block in Markdown.
"markup.raw.inline" = { fg = "orange" } # `Inline code block` in Markdown.
"markup.heading" = { fg = "yellow", modifiers = ["bold"] }
"markup.list" = { fg = "magenta", modifiers = [""] }
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "pink" }
"markup.link" = { fg = "yellow-bright", modifiers = ["bold"] }
"markup.quote" = { fg = "blue" }


# DIAGNOSTICS
"warning" = { fg ="yellow", bg = "bg1" } # Diagnostics warning (gutter)
"error" = { fg = "red", bg = "bg1" } # Diagnostics error (gutter)
"info" = { fg = "blue", bg = "bg1" } # Diagnostics info (gutter)
"hint" = { fg = "green", bg = "bg1" } # Diagnostics hint (gutter)
"diagnostic" = { modifiers = ["underlined"] } # Diagnostics fallback style (editing area)
"diagnostic.error" = { underline = { color = "red", style="line" } } #	Diagnostics error (editing area)
"diagnostic.warning" = { underline = { color = "yellow", style="line" } } #	Diagnostics warning (editing area)
"diagnostic.info" = { underline = { color = "blue", style="line" } } #	Diagnostics info (editing area)
"diagnostic.hint" = { underline = { color = "green", style="line" } } #	Diagnostics hint (editing area)


# SYNTAX HIGHLIGHTING
# These keys match tree-sitter scopes.

"special" = { fg = "fg2", modifiers = ["bold"]   } # Special symbols e.g `?` in Rust, `...` in Hare.
"attribute" = { fg = "red", modifiers = ["italic"]   } # Class attributes, html tag attributes.

"type" = { fg = "cyan", modifiers = []   } # Variable type, like integer or string, including program defined classes, structs etc..
"type.builtin" = { fg = "orange", modifiers = [ "italic"]   } # Primitive types of the language (string, int, float).
"type.enum.variant" = { fg = "orange", modifiers = []   }

"constructor" = { fg = "green", modifiers = ["italic"]   } # Constructor method for a class or struct.

"constant" = { fg = "orange", modifiers = ["italic"]   } # Constant value
"constant.builtin" = { fg = "yellow" } # Special constants like `true`, `false`, `none`, etc.
"constant.builtin.boolean" = { fg = "yellow", modifiers = ["bold", "italic"]   } # True or False.
"constant.character" = { fg = "yellow", modifiers = ["bold"]   } # Constant of character type.
"constant.character.escape" = { fg = "blue", modifiers = ["bold"] } # escape codes like \n.
"constant.numeric"  = { fg = "orange", modifiers = []   } # constant integer or float value.

"string" = { fg = "yellow", modifiers = [] } # String literal.
"string.regexp" = { fg = "yellow", modifiers = ["bold"]   } # Regular expression literal.
"string.special" = { fg = "yellow", modifiers = ["bold"] } # Strings containing a path, URL, etc.
"string.special.url" = { fg = "yellow", modifiers = ["bold", "underline"] } # String containing a web URL.

"comment" = { fg = "comment", modifiers = ["italic"] } # This is a comment.
"comment.block.documentation" = { fg = "comment", modifiers = ["italic"] } # Doc comments, e.g '///' in rust.

"variable" = { fg = "white", modifiers = ["italic"] }  # Variable names.
"variable.builtin" = { fg = "orange-bright", modifiers = ["italic"]   } # Language reserved variables: `this`, `self`, `super`, etc.
"variable.parameter" = { fg = "params", modifiers = ["italic"]   } # Function parameters.
"variable.other.member" = { fg = "white", modifiers = ["italic"]   } # Fields of composite data types (e.g. structs, unions).

"label" = { fg = "cyan", modifiers = ["bold"]   } # lifetimes - Loop labels, among other things.

"punctuation" = { fg = "fg2" } # Any punctuation symbol.
# "punctuation.delimiter" = { fg = "fg2" } # Commas, colons or other delimiter depending on the language.
# "punctuation.bracket" = { fg = "fg2" } # Parentheses, angle brackets, etc.
# "punctuation.special" = { fg = "fg2" } # String interpolation brackets

"keyword" = { fg = "red", modifiers = ["italic"] } # Language reserved keywords.
"keyword.control" = { fg = "orange", modifiers = ["italic"] } # Control keywords.
"keyword.control.conditional" = { fg = "orange-light", modifiers = ["italic"]  } # `if`, `else`, `elif`.
"keyword.control.repeat" = { fg = "red", modifiers = ["italic"]  } # `for`, `while`, `loop`.
"keyword.control.import" = { fg = "export-import", modifiers = ["italic"]  } # `import`, `export` `use`.
"keyword.control.return" = { fg = "magenta-bright", modifiers = ["italic"]   } # `return` in most languages.
"keyword.control.exception" = { fg = "orange-light", modifiers = ["italic"]   } # `try`, `catch`, `raise`/`throw` and related.
"keyword.operator" = { fg = "red", modifiers = ["italic"] } # 'or', 'and', 'in'.
"keyword.directive" = { fg = "pink", modifiers = ["bold"]   } # Preprocessor directives (#if in C...).
"keyword.function" = { fg = "red", modifiers = ["italic"]   } # The keyword to define a funtion: 'def', 'fun', 'fn'.
"keyword.storage" = { fg = "pink", modifiers = ["italic"]   } # Keywords describing how things are stored
"keyword.storage.type" = { fg = "red", modifiers = ["italic"]   } #  The type of something, class, function, var, let, etc.
"keyword.storage.modifier" = { fg = "pink", modifiers = ["italic"] } # Storage modifiers like static, mut, const, ref, etc.

"operator" = {  fg = "fg2" } # Logical, mathematical, and other operators.

"function" = { fg = "green", modifiers = []  }
"function.builtin" = { fg = "red", modifiers = []  }
"function.macro" = { fg = "macros", modifiers = ["italic"]  }
"function.special" = { fg = "blue", modifiers = ["italic"]  } # Preprocessor function in C.
"function.method" = { fg = "green", modifiers = ["italic"]  } # Class / Struct methods.

"tag" = { fg = "green", modifiers = ["italic"]  } # As in <body> for html, css tags.

"namespace" = { fg = "blue", modifiers = ["italic"]  } # Namespace or module identifier.


# Diff ==============================
# Version control changes.

"diff.plus" = "green" # Additions.
"diff.minus" = "red" # Deletions.
"diff.delta" = "blue" # Modifications.
"diff.delta.moved" = "yellow" # Renamed or moved files.

# color palette
[palette]
export-import  = "#8f8d88"
params         = "#dadee1"
black          = "#393b44"
red            = "#e84855"
red-dim        = "#2f2837"
green          = "#23D18C"
green-dim      = "#26343c"
yellow         = "#ffe066"
yellow-bright  = "#e0c989"
macros         = "#b896b8"
blue           = "#97b2dd"
blue-bright    = "#86abdc"
blue-dim       = "#2f2837"
magenta        = "#b99ee5"
magenta-bright = "#a29bfe"
cyan           = "#00cecb"
cyan-bright    = "#97ceca"
cyan-dim       = "#253f4a"
white          = "#dfdfe0"
orange-light   = "#f0aa85"
orange         = "#f49e4c"
orange-bright  = "#f5b987"
pink           = "#ff5d8f"
pink-bright    = "#dc8ed9"
comment        = "#5F6B7B"
# spec
bg0            = "#111821" # bg (status line and float)
bg1            = "#0D1117" # Default bg
bg2            = "#212e3f" # Lighter bg (colorcolm folds)
bg3            = "#121923" # Lighter bg (cursor line)
bg4            = "#1E2939" # Conceal, border fg
fg0            = "#d6d6d7" # Lighter fg
fg1            = "#C9D1D9" # Default fg
fg2            = "#8598B1" # Darker fg (status line)
fg3            = "#71839b" # Darker fg (line numbers, fold colums)
sel0           = "#131a24" # Popup bg, visual selection bg
sel1           = "#131a24" # Popup sel bg, search bg
